module.exports = {
    pathPrefix: "/gatsby-freestyle",
    siteTitle: `Gatsby Freestyle Starter`,
    siteLogo: "/favicon.ico",
    siteUrl: "https://garrynsk.github.io",
    siteDescription: "A GatsbyJS blog starter for hackers.",
    githubAuthor: "garrynsk",
    port: 9000,
    userEmail: `garrynsk@gmail.com`,
    userName: `Zakharova Victoria`,
    userMoto: `Just a scala developer.`,
    avatar: `/img/avatar.jpg`,
    year: `2018`,
    headerBackground: `/img/Flying_Herk_in_the_Clouds.svg`,
    algoliaAppId: process.env.ALGOLIA_APP_ID,
    algoliaApiKey: process.env.ALGOLIA_API_KEY,
    disqusShortname: "garrynsk",
    googleAnalyticsID: "UA-47311644-5",
    githubUrl: "https://garrynsk.github.io",
    twitterUrl: "https://garrynsk.github.io",
    linkednUrl: "https://garrynsk.github.io",
    facebookUrl: "https://garrynsk.github.io",
    themeColor: "#c62828",
    backgroundColor: "#e0e0e0",
}
